n = (input('Digite um valor: '))
print('O tipo primitivo desse valor é', type(n))
print('É Alfanumérico?', n.isalnum())
print('É Alfabético?', n.isalpha())
print('É numérico?', n.isnumeric())
print('Está em maiúsculo?', n.isupper())
print('Está em minúsculo?', n.islower())
print('Só tem espaços?', n.isspace())
print('Está capitalizada?', n.istitle())
