n = str(input('Digite seu nome completo: ')).strip()
nome = n.split()
posicao = len(nome)
print(nome)
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(nome[0]))
print('O Seu nome tem {} posições'.format(posicao))
print('Seu último nome é {}'.format(nome[len(nome)-1]))
